#!/bin/bash

select choix in "push" "pull" "git clone" "quitter"
do
	case $REPLY in
		1)	echo "Message du commit"
			read rep
			git add .
			git commit -m $rep
			git push;;
		2)	git pull;;
		3)	echo "Répertoire à clone"
			read rep
			git clone $rep;;
		4)	break;;
		*)	git status;;
	esac
done


